### ISSUE TITLE
Himalaya Wallet V6 1.5.0

### ISSUE THREAD

**Issue by GreyWalz** [scala-network/scala-electron-gui#5]
hi i am trying to download https://github.com/scala-network/scala-electron-gui/releases/tag/1.5.0  the himalaya wallet, v6 as i had an old stellite wallet which is now gone.. i have my seeds etc. so in order to do the swap i need to download this old wallet, to restore my tokens, then download a newer v7 wallet to do the swap.
I am having trouble with the v6 himalya wallet.. i can download the file, but cannot extract anything, so cannot extract the wallet.. i have tried on 2 x pc's, i have windows 64 and am using the correct download. can you help??

**Comment by Teredic** [comment]
Hello. I wasn't able to reproduce the problem, and extracting the archive worked for me.

However I have uploaded a rar archive, and added an "alternative" zip file (it should have more compatibility with older Windows versions). 

Please tell me if it fixed your problem.

**Comment by GreyWalz** [comment]
Hello 
I am still having trouble I have put it in telegram .. I got that v2 version to download but had to disable some protection but I really should not have to.. now the wallet won’t open it’s frozen and my Malwarebytes has blocked something from the wallet, it’s a RiskWare .BitcoinMiner.generic. ?? 
Tried the RAR file but it’s wants me to download some unzip file and really don’t want to.. so not sure what to do next ? 
Thanks 
Julie

**Comment by Mas7erMind** [comment]
Hello, our platform contains no internal viruses. Unfortunately, Microsoft Defender and other AV programs automatically block crypto software due to its not so great history of rogue projects hijacking computers and servers and turning them into mining facilities, which make money for malicious figures.

This being said, our daemon includes our legit mining software, so this is why it's triggering the AV, but it's a false positive, there is no virus in our files. You can check by yourself on our repo here on GitHub.

**Comment by GreyWalz** [comment]
Hello thanks for your help. I was able to get the old Himalaya wallet open, with my seed, the balance appears to be 0??? I held a large amount of stellite… would this be only because I have not used the swap tool, for the latest wallet yet???? I am hoping so???

Julie

**Comment by GreyWalz** [comment]
Hello I also am putting my old address into the scala explora and nothing is coming up, and restored the himilaya wallet, with zero balance, I had 750K worth of coins in there

Se3zE5dyJ7ENKT3khoLSTBTMy38gpiwWReXa3XZN8R9AB2bu1iMuwLxAnB7mS36YQVTz2XABkjEWuUn94434yJpk2S7DNWn4H

That is my old address
