### ISSUE TITLE
View on explorer button link broken

### ISSUE THREAD

**Issue by AarbozT** [scala-network/scala-electron-gui#9]
Hi!

The button of the view on explorer in the transaction section currently is redirecting to https://scalablocks.com/tx/TRANSACTION_ID_HERE this is not working seems like is broken link or domain name are not working , have to be changed like https://explorer.scalaproject.io/tx?tx_info=TRANSACTION_ID_HERE , this explorer is listed in the https://scala.herominers.com pool. Or another explorer that works! This is happening in the latest version Scala Electron Wallet v2.0.0

**Comment by Teredic** [comment]
Hi !
The problem has already been fixed in the code, the button will work on the next wallet release.
